name: linter

on:
    push:
        paths-ignore:
            - "*.md"
            - "LICENSE"
            - ".gitignore"
            - "Dockerfile"
            - "compose.yaml"
            - ".dockerignore"
            - ".swcrc"
            - ".env*"
    pull_request:
        paths-ignore:
            - "*.md"
            - "LICENSE"
            - ".gitignore"
            - "Dockerfile"
            - "compose.yaml"
            - ".dockerignore"
            - ".swcrc"
            - ".env*"

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "23"

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.cache/yarn
                  key: yarn-${{ hashFiles('yarn.lock') }}
                  restore-keys: yarn-

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Run formatter
              run: yarn format

            - name: Run linter
              run: yarn lint
